### ISSUE TITLE
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

### ISSUE THREAD

**Issue by learner-shx** [shader-slang/slang-torch#9]
Hello,
when I try to run the first example in https://shader-slang.com/slang/user-guide/a1-02-slangpy.html,
I get following message
```
C:\Users\Dell\.conda\envs\surfel_splatting\lib\site-packages\torch\utils\cpp_extension.py:1967: UserWarning: TORCH_CUDA_ARCH_LIST is not set, all archs for visible cards are included for compilation.
If this is not desired, please set os.environ['TORCH_CUDA_ARCH_LIST'].
  warnings.warn(
Traceback (most recent call last):
  File "C:\Users\Dell\.conda\envs\surfel_splatting\lib\site-packages\torch\utils\cpp_extension.py", line 2107, in _run_ninja_build
    subprocess.run(
  File "C:\Users\Dell\.conda\envs\surfel_splatting\lib\subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\WorkSpace\slangTest\111.py", line 4, in <module>
    m = slangtorch.loadModule('square.slang')
  File "C:\Users\Dell\.conda\envs\surfel_splatting\lib\site-packages\slangtorch\slangtorch.py", line 616, in loadModule
    rawModule = _loadModule(fileName, moduleName, buildDir, options, sourceDir=outputFolder, verbose=verbose, includePaths=includePaths, dryRun=False)
  File "C:\Users\Dell\.conda\envs\surfel_splatting\lib\site-packages\slangtorch\slangtorch.py", line 535, in _loadModule
    slangLib, metadata = compileAndLoadModule(
  File "C:\Users\Dell\.conda\envs\surfel_splatting\lib\site-packages\slangtorch\slangtorch.py", line 426, in compileAndLoadModule
    slangLib = _compileAndLoadModule(metadata, sources, moduleName, buildDir, slangSourceDir, verbose)
  File "C:\Users\Dell\.conda\envs\surfel_splatting\lib\site-packages\slangtorch\slangtorch.py", line 465, in _compileAndLoadModule
    return jit_compile(
  File "C:\Users\Dell\.conda\envs\surfel_splatting\lib\site-packages\slangtorch\util\compile.py", line 71, in jit_compile
    _write_ninja_file_and_build_library(
  File "C:\Users\Dell\.conda\envs\surfel_splatting\lib\site-packages\torch\utils\cpp_extension.py", line 1832, in _write_ninja_file_and_build_library
    _run_ninja_build(
  File "C:\Users\Dell\.conda\envs\surfel_splatting\lib\site-packages\torch\utils\cpp_extension.py", line 2122, in _run_ninja_build
    message += f": {error.output.decode(*SUBPROCESS_DECODE_ARGS)}"  # type: ignore[union-attr]
  File "C:\Users\Dell\.conda\envs\surfel_splatting\lib\encodings\oem.py", line 15, in decode
    return oem_decode(input, errors, True)
UnicodeDecodeError: 'cp1' codec can't decode bytes in position 0--1: No mapping for the Unicode character exists in the target code page.
```

My `torch` version is 2.3.0, `cuda` version is 12.0.

**Comment by randallrvr** [comment]
I encounter a very similar issue

**Comment by saipraveenb25** [comment]
I'm not quite able to reproduce this issue. It looks like the build process produced an error, but the reported error occured when trying to print that error. This could be a conda environment issue. 

Could you try passing `verbose=True` as an extra parameter to `loadModule` and paste the output?

**Comment by learner-shx** [comment]
> I'm not quite able to reproduce this issue. It looks like the build process produced an error, but the reported error occured when trying to print that error. This could be a conda environment issue.
> 
> Could you try passing `verbose=True` as an extra parameter to `loadModule` and paste the output?

Thank you! After updating Visual Studio and MSVC, I created a new Conda environment and the error disappeared.
